[package]
name = "tank_dice"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.95"
directories = "6.0.0"
ratatui = { version = "0.29.0", features = ["unstable-widget-ref"] }
ron = "0.8.1"
serde = "1.0.217"
serde_derive = "1.0.217"
tui-input = "0.11.1"
